### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jdbranham** [smtadmin/nga-oe-java#93]
Hey, I get to open the first issue! 😁   
Where would I access the documentation to use this?  

Also, I might be looking at the wrong repo. I'm looking to emit events to HMF.

**Comment by egeneroli** [comment]
Hi Jeremy,

This is the correct repo. Documentation on how to use can be found here: https://discourse.dso.xc.nga.mil/t/hmf-integration/668

**Comment by jdbranham** [comment]
Nice! Thanks Evan
